# Base image, e.g. tensorflow/tensorflow:1.7.0
FROM tensorflow/tensorflow:1.8.0-gpu

LABEL maintainer='G. Cavallaro (FZJ), M. Goetz (KIT), V. Kozlov (KIT)'
# 2D semantic segmentation (Vaihingen dataset)

RUN apt-get update && \ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

# Set LANG environment
ENV LANG C.UTF-8

# Set the working directory
WORKDIR /app

# Script to run pylint
COPY 2dsemseg/tests/run_pylint.sh /app

# Copy the current directory contents into the container at /app
ADD . /app

# Install pylint and python packages listed in test-requirements.txt
RUN pip --no-cache-dir install -r /app/requirements.txt && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

