##################
# This is to build Docker image for development, 
# i.e. it contains all right packages but 
# application source code is mounted from HOST (~/2dsemseg as pulled from github)
#
# To build the image, run from ~/2dsemseg as
# $ docker build -t dockerimage -f docker/Dockerfile.dev .
#
# Later to use the image and access its shell:
# udocker run -v $HOSTDIR/2dsemseg:/app dockerimage /bin/bash
#
# REMINDER! You may also need to mount other directories, e.g. for data
##################
# Base image
FROM tensorflow/tensorflow:1.8.0

LABEL maintainer='G. Cavallaro (FZJ), M. Goetz (KIT), V. Kozlov (KIT)'
# 2D semantic segmentation (Vaihingen dataset)

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y --no-install-recommends \
         git \
         curl \
         wget \
         python-setuptools \
         python-pip \
         python-wheel && \ 
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

# Set the working directory
WORKDIR /app

# Install python packages listed in requirements.txt
COPY requirements-dev.txt /root
RUN pip --no-cache-dir install -r /root/requirements-dev.txt && \
    rm -rf /root/.cache/pip/* && \
    rm -rf /tmp/*

## REMINDER: Tensorflow Docker Images already EXPOSE ports 6006 and 8888

## When running the container do NOT forget to mount data and models directories accordingly!
## $HOSTDIR/data -> /app/data
## $HOSTDIR/models -> /app/models
